version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: proctoring_dev
      MYSQL_USER: proctor
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password --max_connections=5000
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  zookeeper:
    image: bitnamilegacy/zookeeper:3.8.1
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: bitnamilegacy/kafka:3.7.1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  auth-service:
    build: ../backend/auth-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/proctoring_dev
      SPRING_DATASOURCE_USERNAME: proctor
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_REDIS_HOST: redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_PUBLIC_KEY_LOCATION: classpath:jwt-public.pem
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  event-ingest-service:
    build: ../backend/event-ingest-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/proctoring_dev
      SPRING_DATASOURCE_USERNAME: proctor
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_REDIS_HOST: redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_PUBLIC_KEY_LOCATION: classpath:jwt-public.pem
    volumes:
      - ./thumbnails:/tmp/proctoring/thumbnails
    ports:
      - "8082:8082"
    depends_on:
      kafka:
        condition: service_started
      redis:
        condition: service_started
      mysql:
        condition: service_healthy

  rules-engine:
    build: ../backend/rules-engine
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/proctoring_dev
      SPRING_DATASOURCE_USERNAME: proctor
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_REDIS_HOST: redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_PUBLIC_KEY_LOCATION: classpath:jwt-public.pem
    ports:
      - "8083:8083"
    depends_on:
      kafka:
        condition: service_started
      redis:
        condition: service_started
      mysql:
        condition: service_healthy

  dashboard-api:
    build: ../backend/dashboard-api
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/proctoring_dev
      SPRING_DATASOURCE_USERNAME: proctor
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_REDIS_HOST: redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_PUBLIC_KEY_LOCATION: classpath:jwt-public.pem
    ports:
      - "8084:8084"
    depends_on:
      mysql:
        condition: service_healthy

  client:
    build: ../client/nextjs-app
    environment:
      NEXT_PUBLIC_EVENT_INGEST_URL: http://localhost:8082/proctoring/events/batch
      NEXT_PUBLIC_SESSION_START_URL: http://localhost:8082/proctoring/sessions/start
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - event-ingest-service
